version: "3.7"

services:
  api:
    image: georgnrm/georg-api:v2.1.1
    container_name: georg-api
    restart: always
    ports:
      - 8180:8180
    volumes:
      - ./project-initdata.yml:/usr/src/myapp/project-initdata.yml
    external_links:
      - pelias_api:pelias_api
    networks:
      - default
      - pelias

  ui:
    image: georgnrm/georg-ui:v1.2.2
    container_name: georg-ui
    restart: always
    expose:
      - "80"
    networks:
      - default
    depends_on:
      - api

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    # environment:
    #   - VIRTUAL_HOST=georg-stage.nrm.se
    volumes:
      - ./webserver/app.conf:/etc/nginx/conf.d/app.conf:ro
    networks:
      - default

networks:
  default:
    external:
      name: proxy_default
  pelias:
    external:
      name: pelias_default
